### ISSUE TITLE
2024/6/19 该教程依旧适用

### ISSUE THREAD

**Issue by kdjhfa** [yukaiji/buildVpn#49]

**Comment by kdjhfa** [comment]
不过服务器最低价变成5$了，有点用不起了。。。

**Comment by m178** [comment]
> 不过服务器最低价变成5$了，有点用不起了。。。

为什么我看到的最低都是30啊，没看到你说的5$的啊

**Comment by kdjhfa** [comment]
@m178 你应该是第二张图选了前一个吧？话说哥们拼车吗？一个人用我觉得有点小贵，500G也有点多了，我个人主要是求稳定才打算自建的，主要是用gpt
![屏幕截图 2024-06-21 163611](https://github.com/yukaiji/buildVpn/assets/147389286/3291fcd0-7ab0-4006-bcac-78f8099f6794)
![image](https://github.com/yukaiji/buildVpn/assets/147389286/c82f847b-0293-4a9a-b030-e8a3d37c073b)

**Comment by m178** [comment]
> @m178你应该第二张图选前一个吧？ 话说哥们儿吗？ 一个人觉得有点小贵，500G也有点多了，我个人的重点求稳定才打算自建重点用gpt， ![2024-06-21 163611](https://private-user-images.githubusercontent.com/147389286/341699781-3291fcd0-7ab0-4006-bcac-78f8099f6794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjA5MTAsIm5iZiI6MTcxODk2MDYxMCwicGF0aCI6Ii8xNDczODkyODYvMzQxNjk5NzgxLTMyOTFmY2QwLTdhYjAtNDAwNi1iY2FjLTc4ZjgwOTlmNjc5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwOTAzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGNmOGM5OTgyZDFlNDlkZTAyMTY1OTU0N2U3NjlkZmQ2YzQyMmUyNzg1NWMyYmNmZDgyNjljYTc3MjY3MTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.31bhgITOZh3l-8FWddFvffcqGxxQDyxyJ-u11tviQs0) ![图像](https://private-user-images.githubusercontent.com/147389286/341699893-c82f847b-0293-4a9a-b030-e8a3d37c073b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjA5MTAsIm5iZiI6MTcxODk2MDYxMCwicGF0aCI6Ii8xNDczODkyODYvMzQxNjk5ODkzLWM4MmY4NDdiLTAyOTMtNGE5YS1iMDMwLWU4YTNkMzdjMDczYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwOTAzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWJlMTBiNjFhMDMwMDRlYjNhYTdhMTFkYzU0NGExNTg1MDE2YTRjOGMwYzViNTBjNDUzYmY5ODA3MDhhZDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O6lbQgvvEN4zWzDk6VEtNDa0ETQE4FRSM-h2Fd_Nf-s)

哦哦，看到啦，谢谢，这个我试着用了一下，感觉延迟有点大emmm

**Comment by m178** [comment]
> @m178你应该第二张图前一个吧？ 话说我们几个人觉得有点小贵，500G也有点多了，我个人的重点稳定才打算自建重点用gpt， ![2024-06-21 163611](https://private-user-images.githubusercontent.com/147389286/341699781-3291fcd0-7ab0-4006-bcac-78f8099f6794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjA5MTAsIm5iZiI6MTcxODk2MDYxMCwicGF0aCI6Ii8xNDczODkyODYvMzQxNjk5NzgxLTMyOTFmY2QwLTdhYjAtNDAwNi1iY2FjLTc4ZjgwOTlmNjc5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwOTAzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGNmOGM5OTgyZDFlNDlkZTAyMTY1OTU0N2U3NjlkZmQ2YzQyMmUyNzg1NWMyYmNmZDgyNjljYTc3MjY3MTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.31bhgITOZh3l-8FWddFvffcqGxxQDyxyJ-u11tviQs0) ![图像](https://private-user-images.githubusercontent.com/147389286/341699893-c82f847b-0293-4a9a-b030-e8a3d37c073b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjA5MTAsIm5iZiI6MTcxODk2MDYxMCwicGF0aCI6Ii8xNDczODkyODYvMzQxNjk5ODkzLWM4MmY4NDdiLTAyOTMtNGE5YS1iMDMwLWU4YTNkMzdjMDczYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwOTAzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWJlMTBiNjFhMDMwMDRlYjNhYTdhMTFkYzU0NGExNTg1MDE2YTRjOGMwYzViNTBjNDUzYmY5ODA3MDhhZDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O6lbQgvvEN4zWzDk6VEtNDa0ETQE4FRSM-h2Fd_Nf-s)

感觉延迟有点大

**Comment by kdjhfa** [comment]
@m178 还行吧？我的vpn大概300毫秒
![image](https://github.com/yukaiji/buildVpn/assets/147389286/3d14e4f8-c189-4a20-83ed-634daa936e6b)

**Comment by hanyang6278** [comment]
我想拼个车 @kdjhfa

**Comment by kdjhfa** [comment]
@hanyang6278 我现在vultr的免费部分用完了，然后跑去白嫖azure的新人1年特权了，而且我发现azure的好像有更弱性能但是更便宜的服务器，之后估计也是用azure

**Comment by kdjhfa** [comment]
@hanyang6278  我现在vultr的免费部分用完了，然后跑去白嫖azure的新人1年特权了，暂时是不需要拼车了

**Comment by MrKINGFS** [comment]
请教一下，我这边按照教程安装成功了，手机连也成功了一下，但是刷新页面就再也不行了，ping 跟 telnet 也是通的
看shadow日志是提示  
2024-08-20 18:27:17 ERROR    tcprelay.py:1096 can not parse header when handling connection from ::ffff:172.81.126.189:60100

请问这是服务器被墙了（ping 跟 telnet 也是通的，端口也开放了）还是什么原因呢？

**Comment by kdjhfa** [comment]
@MrKINGFS ping能通就应该不是被墙了，不过我最近都是直接用ssr的docker部署了，因为方便管理一点，所以可能不太能帮到你
